using System.Reflection;
using MiniORM.Core.Attributes;

namespace MiniORM.Core;

/// <summary>
/// Holds cached metadata about an entity type.
/// 
/// Design Pattern: Flyweight Pattern
/// - We create one instance per entity type and reuse it.
/// </summary>
public class EntityMetadata
{
    public Type EntityType { get; }
    public string TableName { get; }
    public string Schema { get; }
    public string FullTableName { get; }
    public PropertyMetadata? PrimaryKey { get; private set; }
    public IReadOnlyList<PropertyMetadata> Properties { get; }
    public IReadOnlyList<PropertyMetadata> MappedProperties { get; }

    public EntityMetadata(Type entityType)
    {
        EntityType = entityType ?? throw new ArgumentNullException(nameof(entityType));

        // Get table name from attribute or use class name
        var tableAttr = entityType.GetCustomAttribute<TableAttribute>();
        TableName = tableAttr?.Name ?? entityType.Name;
        Schema = tableAttr?.Schema ?? "";
        FullTableName = string.IsNullOrEmpty(Schema) 
            ? $"[{TableName}]" 
            : $"[{Schema}].[{TableName}]";

        // Get all public instance properties
        var properties = entityType
            .GetProperties(BindingFlags.Public | BindingFlags.Instance)
            .Where(p => p.CanRead && p.CanWrite)
            .Select(p => new PropertyMetadata(p))
            .ToList();

        Properties = properties;
        MappedProperties = properties.Where(p => !p.IsNotMapped).ToList();
        PrimaryKey = properties.FirstOrDefault(p => p.IsPrimaryKey);

        // Convention: Try to find a property named "Id" or "{EntityName}Id"
        if (PrimaryKey == null)
        {
            PrimaryKey = properties.FirstOrDefault(p =>
                p.PropertyName.Equals("Id", StringComparison.OrdinalIgnoreCase) ||
                p.PropertyName.Equals($"{entityType.Name}Id", StringComparison.OrdinalIgnoreCase));

            if (PrimaryKey != null)
            {
                // Mark it as primary key by convention
                PrimaryKey.IsPrimaryKey = true;
                PrimaryKey.IsAutoGenerated = true;
            }
        }

        if (PrimaryKey == null)
        {
            throw new InvalidOperationException(
                $"Entity '{entityType.Name}' must have a primary key. " +
                "Use [PrimaryKey] attribute or name a property 'Id'.");
        }
    }

    /// <summary>
    /// Gets properties that should be included in INSERT statements.
    /// Excludes auto-generated primary keys.
    /// </summary>
    public IEnumerable<PropertyMetadata> GetInsertProperties()
    {
        return MappedProperties.Where(p =>
            !p.IsPrimaryKey || !p.IsAutoGenerated);
    }

    /// <summary>
    /// Gets properties that should be included in UPDATE statements.
    /// Excludes primary keys.
    /// </summary>
    public IEnumerable<PropertyMetadata> GetUpdateProperties()
    {
        return MappedProperties.Where(p => !p.IsPrimaryKey);
    }
}
