using MiniORM.Core;
using MiniORM.Core.Attributes;

namespace MiniORM.Tests;

/// <summary>
/// Tests for EntityMetadata and PropertyMetadata classes.
/// </summary>
public class EntityMetadataTests
{
    #region Table Name Tests

    [Fact]
    public void GetMetadata_WithTableAttribute_ReturnsAttributeTableName()
    {
        // Act
        var metadata = EntityMapper.GetMetadata<TestCustomer>();

        // Assert
        Assert.Equal("TestCustomers", metadata.TableName);
    }

    [Fact]
    public void GetMetadata_WithoutTableAttribute_ReturnsClassName()
    {
        // Arrange - EntityWithoutAttribute uses class name as table name
        var metadata = EntityMapper.GetMetadata<EntityWithoutTableAttribute>();

        // Assert
        Assert.Equal("EntityWithoutTableAttribute", metadata.TableName);
    }

    #endregion

    #region Primary Key Tests

    [Fact]
    public void GetMetadata_WithPrimaryKeyAttribute_FindsPrimaryKey()
    {
        // Act
        var metadata = EntityMapper.GetMetadata<TestCustomer>();

        // Assert
        Assert.NotNull(metadata.PrimaryKey);
        Assert.Equal("Id", metadata.PrimaryKey.PropertyName);
        Assert.True(metadata.PrimaryKey.IsPrimaryKey);
        Assert.True(metadata.PrimaryKey.IsAutoGenerated);
    }

    [Fact]
    public void GetMetadata_WithIdConvention_FindsPrimaryKeyByConvention()
    {
        // Act
        var metadata = EntityMapper.GetMetadata<EntityWithIdConvention>();

        // Assert
        Assert.NotNull(metadata.PrimaryKey);
        Assert.Equal("Id", metadata.PrimaryKey.PropertyName);
        Assert.True(metadata.PrimaryKey.IsPrimaryKey);
    }

    #endregion

    #region Property Metadata Tests

    [Fact]
    public void GetMetadata_WithColumnAttribute_ReturnsCustomColumnName()
    {
        // Act
        var metadata = EntityMapper.GetMetadata<TestCustomer>();

        // Assert
        var nameProperty = metadata.MappedProperties.First(p => p.PropertyName == "Name");
        Assert.Equal("CustomerName", nameProperty.ColumnName);
    }

    [Fact]
    public void GetMetadata_WithoutColumnAttribute_ReturnsPropertyName()
    {
        // Act
        var metadata = EntityMapper.GetMetadata<TestCustomer>();

        // Assert
        var ageProperty = metadata.MappedProperties.First(p => p.PropertyName == "Age");
        Assert.Equal("Age", ageProperty.ColumnName);
    }

    [Fact]
    public void GetMetadata_WithNotMappedAttribute_ExcludesProperty()
    {
        // Act
        var metadata = EntityMapper.GetMetadata<TestCustomer>();

        // Assert
        var displayNameProperty = metadata.MappedProperties.FirstOrDefault(p => p.PropertyName == "DisplayName");
        Assert.Null(displayNameProperty);
    }

    [Fact]
    public void GetMetadata_WithForeignKeyAttribute_IdentifiesForeignKey()
    {
        // Act
        var metadata = EntityMapper.GetMetadata<TestOrder>();

        // Assert
        var customerIdProperty = metadata.MappedProperties.First(p => p.PropertyName == "CustomerId");
        Assert.True(customerIdProperty.IsForeignKey);
        Assert.Equal(typeof(TestCustomer), customerIdProperty.ForeignKeyType);
    }

    #endregion

    #region Metadata Caching Tests

    [Fact]
    public void GetMetadata_CalledTwice_ReturnsSameInstance()
    {
        // Act
        var metadata1 = EntityMapper.GetMetadata<TestCustomer>();
        var metadata2 = EntityMapper.GetMetadata<TestCustomer>();

        // Assert
        Assert.Same(metadata1, metadata2);
    }

    #endregion

    #region Insert/Update Property Tests

    [Fact]
    public void GetInsertProperties_ExcludesAutoGeneratedPrimaryKey()
    {
        // Act
        var metadata = EntityMapper.GetMetadata<TestCustomer>();
        var insertProps = metadata.GetInsertProperties().ToList();

        // Assert
        Assert.DoesNotContain(insertProps, p => p.PropertyName == "Id");
    }

    [Fact]
    public void GetUpdateProperties_ExcludesPrimaryKey()
    {
        // Act
        var metadata = EntityMapper.GetMetadata<TestCustomer>();
        var updateProps = metadata.GetUpdateProperties().ToList();

        // Assert
        Assert.DoesNotContain(updateProps, p => p.PropertyName == "Id");
    }

    #endregion

    #region Test Helper Classes

    public class EntityWithoutTableAttribute : EntityBase
    {
        public int Id { get; set; }
        public string Name { get; set; } = "";
    }

    public class EntityWithIdConvention : EntityBase
    {
        public int Id { get; set; }
        public string Value { get; set; } = "";
    }

    #endregion
}
