using System.Linq.Expressions;
using MiniORM.Core.Query;

namespace MiniORM.Core.Repository;

/// <summary>
/// Generic repository implementation.
/// 
/// Design Pattern: Repository Pattern
/// - Implements IRepository interface
/// - Uses Query Builders for SQL generation
/// - Uses EntityMapper for object mapping
/// </summary>
public class Repository<TEntity, TKey> : IRepository<TEntity, TKey>
    where TEntity : class, new()
{
    protected readonly DbContext Context;
    protected readonly EntityMetadata Metadata;

    public Repository(DbContext context)
    {
        Context = context ?? throw new ArgumentNullException(nameof(context));
        Metadata = EntityMapper.GetMetadata<TEntity>();
    }

    #region Query Operations

    public virtual TEntity? GetById(TKey id)
    {
        var query = new SqlQueryBuilder()
            .Select<TEntity>()
            .From<TEntity>()
            .Where(Metadata.PrimaryKey!.ColumnName, id);

        var sql = query.Build();
        using var reader = Context.ExecuteReader(sql, query.GetParameterTuples());
        
        if (reader.Read())
        {
            return EntityMapper.MapFromReader<TEntity>(reader);
        }
        return null;
    }

    public virtual IEnumerable<TEntity> GetAll()
    {
        var query = new SqlQueryBuilder()
            .Select<TEntity>()
            .From<TEntity>();

        var sql = query.Build();
        using var reader = Context.ExecuteReader(sql);
        return EntityMapper.MapAllFromReader<TEntity>(reader);
    }

    public virtual IEnumerable<TEntity> Find(Expression<Func<TEntity, bool>> predicate)
    {
        var query = new SqlQueryBuilder()
            .Select<TEntity>()
            .From<TEntity>();

        // Parse the expression to SQL WHERE clause
        var parser = new ExpressionParser();
        var whereClause = parser.Parse(predicate, query);
        
        if (!string.IsNullOrEmpty(whereClause))
        {
            query.Where(whereClause);
        }

        var sql = query.Build();
        using var reader = Context.ExecuteReader(sql, query.GetParameterTuples());
        return EntityMapper.MapAllFromReader<TEntity>(reader);
    }

    public virtual TEntity? FirstOrDefault(Expression<Func<TEntity, bool>> predicate)
    {
        var query = new SqlQueryBuilder()
            .Select<TEntity>()
            .From<TEntity>()
            .Take(1);

        var parser = new ExpressionParser();
        var whereClause = parser.Parse(predicate, query);
        
        if (!string.IsNullOrEmpty(whereClause))
        {
            query.Where(whereClause);
        }

        var sql = query.Build();
        using var reader = Context.ExecuteReader(sql, query.GetParameterTuples());
        
        if (reader.Read())
        {
            return EntityMapper.MapFromReader<TEntity>(reader);
        }
        return null;
    }

    public virtual bool Any(Expression<Func<TEntity, bool>>? predicate = null)
    {
        return Count(predicate) > 0;
    }

    public virtual int Count(Expression<Func<TEntity, bool>>? predicate = null)
    {
        var query = new SqlQueryBuilder()
            .From<TEntity>();

        if (predicate != null)
        {
            var parser = new ExpressionParser();
            var whereClause = parser.Parse(predicate, query);
            if (!string.IsNullOrEmpty(whereClause))
            {
                query.Where(whereClause);
            }
        }

        var sql = query.BuildCount();
        var result = Context.ExecuteScalar(sql, query.GetParameterTuples());
        return Convert.ToInt32(result);
    }

    #endregion

    #region Command Operations

    public virtual TEntity Add(TEntity entity)
    {
        var insertQuery = new InsertQueryBuilder()
            .Into<TEntity>()
            .Values(entity);

        var sql = insertQuery.Build();
        var id = Context.ExecuteScalar(sql, insertQuery.GetParameterTuples());

        // Set the generated ID on the entity
        if (id != null && Metadata.PrimaryKey!.IsAutoGenerated)
        {
            var convertedId = Convert.ChangeType(id, Metadata.PrimaryKey.PropertyType);
            Metadata.PrimaryKey.SetValue(entity, convertedId);
        }

        // Update entity state
        if (entity is EntityBase entityBase)
        {
            entityBase.State = EntityState.Unchanged;
        }

        return entity;
    }

    public virtual void Update(TEntity entity)
    {
        var updateQuery = new UpdateQueryBuilder()
            .Table<TEntity>()
            .SetAll(entity)
            .WherePrimaryKey(entity);

        var sql = updateQuery.Build();
        Context.ExecuteNonQuery(sql, updateQuery.GetParameterTuples());

        // Update entity state
        if (entity is EntityBase entityBase)
        {
            entityBase.State = EntityState.Unchanged;
        }
    }

    public virtual void Delete(TEntity entity)
    {
        var deleteQuery = new DeleteQueryBuilder()
            .From<TEntity>()
            .WherePrimaryKey(entity);

        var sql = deleteQuery.Build();
        Context.ExecuteNonQuery(sql, deleteQuery.GetParameterTuples());

        // Update entity state
        if (entity is EntityBase entityBase)
        {
            entityBase.State = EntityState.Detached;
        }
    }

    public virtual void Delete(TKey id)
    {
        var deleteQuery = new DeleteQueryBuilder()
            .From<TEntity>()
            .WherePrimaryKey<TEntity, TKey>(id);

        var sql = deleteQuery.Build();
        Context.ExecuteNonQuery(sql, deleteQuery.GetParameterTuples());
    }

    #endregion
}

/// <summary>
/// Repository with int as default key type.
/// </summary>
public class Repository<TEntity> : Repository<TEntity, int>, IRepository<TEntity>
    where TEntity : class, new()
{
    public Repository(DbContext context) : base(context)
    {
    }
}
